export const AUTH_DISCARD_TOKEN = 'AUTH_DISCARD_TOKEN';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';

export const VEHICLE_GET_DATA = 'VEHICLE_GET_DATA';
export const CONTACT_GET_USERS = 'CONTACT_GET_USERS';
export const SERVICE_GET_SERVICES = 'SERVICE_GET_SERVICES';
export const SERVICE_GET_TIME_AVAILABLE = 'SERVICE_GET_TIME_AVAILABLE';
export const BOOKING_ADMIN_BOOKING = 'BOOKING_ADMIN_BOOKING';

export const API_REQUEST_SEND = 'API_REQUEST_SEND';
export const API_REQUEST_SUCCESS = 'API_REQUEST_SUCCESS';
export const API_REQUEST_ERROR = 'API_REQUEST_ERROR';
